#!/usr/bin/env bash
git init -qqq
git remote add origin https://github.com/ndk23071998/magento-docker-template
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.gitignore ./
rm -rf compose .git
git init

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh
